# Generated by Django 5.1.3 on 2025-12-04 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profesor", models.CharField(max_length=100)),
                ("fecha", models.DateField()),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaResiduos",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ClaseHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seccion", models.CharField(max_length=200)),
                ("profesor", models.CharField(max_length=100)),
                ("asignatura", models.CharField(max_length=100)),
                ("horario", models.CharField(max_length=100)),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=150, unique=True)),
                ("contraseña", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="HistorialRetiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_retiro", models.DateTimeField(auto_now_add=True)),
                ("contenedor_origen", models.CharField(max_length=50)),
                ("tipo_residuo", models.CharField(max_length=50)),
                (
                    "cantidad_peso",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("cantidad_unidades", models.IntegerField(default=0)),
                ("detalle", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoResiduos",
            fields=[
                ("id_tipo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_residuo", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField()),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.categoriaresiduos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Residuo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contenedor_id",
                    models.CharField(
                        blank=True,
                        help_text="Destino del residuo (Compostera, Líquidos, Unidades)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("seccion", models.CharField(max_length=10)),
                ("profesor", models.CharField(max_length=100)),
                ("asignatura", models.CharField(max_length=100)),
                ("horario", models.CharField(max_length=100)),
                ("numero_clase", models.IntegerField(blank=True, null=True)),
                ("hora_escaneo", models.DateTimeField(auto_now_add=True)),
                (
                    "peso",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("unidad", models.IntegerField(blank=True, null=True)),
                ("retirado", models.BooleanField(default=False)),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="residuos_categoria",
                        to="app.categoriaresiduos",
                    ),
                ),
                (
                    "subtipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="residuos_tipo",
                        to="app.tiporesiduos",
                    ),
                ),
            ],
            options={
                "unique_together": {("asignatura", "seccion", "numero_clase")},
            },
        ),
    ]
