# Generated by Django 5.1.3 on 2026-01-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                (
                    "tipo_residuo",
                    models.CharField(
                        choices=[
                            ("organico", "Orgánico"),
                            ("inorganico", "Inorgánico"),
                            ("liquido", "Liquido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["tipo_residuo", "nombre"],
            },
        ),
    ]
