# Generated by Django 5.1.3 on 2026-01-11 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_destino"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialretiro",
            name="destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retiros",
                to="app.destino",
            ),
        ),
        migrations.AlterField(
            model_name="destino",
            name="tipo_residuo",
            field=models.CharField(
                choices=[
                    ("organicos", "Organicos"),
                    ("inorganicos", "Inorgánicos"),
                    ("liquidos", "Liquidos"),
                ],
                max_length=20,
            ),
        ),
    ]
