# Generated by Django 5.1.3 on 2026-01-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_historialretiro_destino_alter_destino_tipo_residuo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destino",
            name="tipo_residuo",
            field=models.CharField(
                choices=[
                    ("organico", "Organicos"),
                    ("inorganico", "Inorganicos"),
                    ("liquido", "Liquidos"),
                ],
                max_length=20,
            ),
        ),
    ]
