# Generated by Django 5.1.3 on 2026-01-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_destino_tipo_residuo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destino",
            name="tipo_residuo",
            field=models.CharField(
                choices=[
                    ("Organicos", "Organicos"),
                    ("Inorganicos", "Inorganicos"),
                    ("Liquidos", "Liquidos"),
                ],
                max_length=20,
            ),
        ),
    ]
