# Generated by Django 5.1.3 on 2026-01-11 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_destino_tipo_residuo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="destino",
            options={"ordering": ["categoria__nombre", "nombre"]},
        ),
        migrations.RemoveField(
            model_name="destino",
            name="tipo_residuo",
        ),
        migrations.AddField(
            model_name="destino",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="destinos",
                to="app.categoriaresiduos",
            ),
        ),
    ]

