# Generated by Django 6.0.1 on 2026-01-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_categoria_to_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinos', to='app.categoriaresiduos'),
        ),
    ]
