# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_backfill_clasehorario_fecha_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarios",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha del ultimo cambio de clave para controlar caducidad.",
                null=True,
            ),
        ),
    ]
