# Generated by Django 5.2.15 on 2026-07-10 17:24

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def agregar_columnas_faltantes(apps, schema_editor):
    """Permite avanzar desde la variante 0019 distribuida anteriormente."""
    campos = (
        ("ClaseHorario", "export_error", models.TextField(blank=True, default="")),
        ("ClaseHorario", "export_residuos_path", models.CharField(blank=True, max_length=500)),
        ("ClaseHorario", "export_retiros_path", models.CharField(blank=True, max_length=500)),
        ("ClaseHorario", "exportado", models.BooleanField(db_index=True, default=False)),
        ("ClaseHorario", "exportado_at", models.DateTimeField(blank=True, null=True)),
        (
            "Residuo",
            "created_at",
            models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        ("Residuo", "manual_entry", models.BooleanField(db_index=True, default=False)),
        (
            "Residuo",
            "manual_reason",
            models.CharField(blank=True, max_length=255, null=True),
        ),
    )

    for model_name, field_name, field in campos:
        model = apps.get_model("app", model_name)
        table = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(
                    cursor,
                    table,
                )
            }
        if field_name in columns:
            continue
        field.set_attributes_from_name(field_name)
        schema_editor.add_field(model, field)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_seed_talleres_precargados"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    agregar_columnas_faltantes,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="clasehorario",
                    name="export_error",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="clasehorario",
                    name="export_residuos_path",
                    field=models.CharField(blank=True, max_length=500),
                ),
                migrations.AddField(
                    model_name="clasehorario",
                    name="export_retiros_path",
                    field=models.CharField(blank=True, max_length=500),
                ),
                migrations.AddField(
                    model_name="clasehorario",
                    name="exportado",
                    field=models.BooleanField(db_index=True, default=False),
                ),
                migrations.AddField(
                    model_name="clasehorario",
                    name="exportado_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="residuo",
                    name="created_at",
                    field=models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                migrations.AddField(
                    model_name="residuo",
                    name="manual_entry",
                    field=models.BooleanField(db_index=True, default=False),
                ),
                migrations.AddField(
                    model_name="residuo",
                    name="manual_reason",
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="residuo",
            name="hora_escaneo",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="residuo",
            index=models.Index(
                fields=["manual_entry", "hora_escaneo"],
                name="app_residuo_manual__078a84_idx",
            ),
        ),
    ]
