# Generated by Django 5.2.15 on 2026-07-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_clasehorario_export_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clasehorario",
            name="tipo_taller",
            field=models.CharField(
                choices=[
                    ("recuperacion_clases", "Recuperación de clases"),
                    ("sesion_extra", "Sesión extra"),
                    ("actividad_extra_programatica", "Actividad extra programática"),
                    ("nueva_actividad", "Nueva actividad"),
                ],
                db_index=True,
                default="nueva_actividad",
                max_length=40,
            ),
        ),
    ]
