# Generated by Django 5.2.15 on 2026-07-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_clasehorario_tipo_taller"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actividad",
            options={"verbose_name": "Taller", "verbose_name_plural": "Talleres"},
        ),
    ]
