# Generated by Django 5.2.15 on 2026-07-10 22:38

from django.db import migrations, models
from django.utils import timezone


def marcar_exportaciones_historicas_entregadas(apps, schema_editor):
    ClaseHorario = apps.get_model("app", "ClaseHorario")
    ahora = timezone.now()
    ClaseHorario.objects.filter(exportado=True).update(
        export_residuos_descargado_at=ahora,
        export_retiros_descargado_at=ahora,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_actividad_verbose_taller"),
    ]

    operations = [
        migrations.AddField(
            model_name="clasehorario",
            name="export_residuos_descargado_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clasehorario",
            name="export_retiros_descargado_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            marcar_exportaciones_historicas_entregadas,
            migrations.RunPython.noop,
        ),
    ]
