from django.urls import path
from . import views
from .views import login_view, logout_view,obtener_datos_api

urlpatterns = [
    path('registrar-evento/', views.taller, name='registrar_evento'),
    path('taller-form/', views.taller, name='confimar_clase'),
    path('obtener-datos/', views.obtener_datos),
    path("api/obtener-datos/", obtener_datos_api, name="api_obtener_datos"),
    path('residuos/', views.residuos, name='residuos'),
    path('fuerahorario/', views.fuera_horario, name='fuerahorario'),
    path('codigo-qr/', views.pagina_codigo_qr, name='codigo_qr'),
    path('codigo-qr/imagen/', views.generar_codigo, name='generar_codigo'),
    path('', views.ver_qr, name='ver_qr'),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("profesor/acceso-qr/", views.acceso_profesor_qr, name="acceso_profesor_qr"),
    path("profesor/acceso-qr/imagen/", views.generar_qr_profesor, name="generar_qr_profesor"),
    path('profesor/', views.profesor, name='profesor'),
    path('profesor/archivar-pasadas/', views.archivar_actividades_pasadas, name='archivar_actividades_pasadas'),
    path('profesor/eliminar-actividad/<int:id>/', views.eliminar_actividad, name='eliminar_actividad'),
    path("actualizar-residuo/", views.actualizar_residuo, name="actualizar_residuo"),
    path("confirmar-residuo/", views.confirmar_residuo, name="confirmar_residuo"),
    path("guardar/", views.guardar, name="guardar"),
    path("ingreso-manual/", views.ingreso_manual_olvido, name="ingreso_manual_olvido"),
    path('usuarios/', views.usuarios_view, name='usuarios'),
    path('usuarios/eliminarUsuario/<int:id_usuario>', views.eliminarUsuario, name='eliminarUsuario'),
    path('usuarios/editarUsuario/<int:id_usuario>', views.editarUsuario, name='editarUsuario'),
    path('gestionCategorias/', views.gestionCategorias, name='gestionCategorias'),
    path('gestionCategorias/eliminarCategoria/<int:id_categoria>', views.eliminarCategoria, name='eliminarCategoria'),
    path('gestionCategorias/editarCategoria/<int:id_categoria>', views.editarCategoria, name='editarCategorias'),
    path('base', views.base_view, name='base'),
    path('receive_weight/', views.receive_weight, name='receive_weight'),
    path('api/update_weight/', views.receive_weight_api, name='api_update_weight'),
    path('balanza/leer/', views.balanza_leer, name='balanza_leer'),
    path('balanza/diagnostico/', views.balanza_diagnostico, name='balanza_diagnostico'),
    path('last_weight/', views.last_weight, name='last_weight'),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("api/dashboard/unidades/", views.dashboard_unidades, name="dashboard_unidades"),
    path("dashboard/pendientes/<int:residuo_id>/cerrar/", views.cerrar_residuo_pendiente, name="cerrar_residuo_pendiente"),
    path("dashboard/limpiar/", views.limpiar_panel, name="limpiar_panel"),
    path("seleccionar-actividad/<int:id>/", views.seleccionar_actividad, name="seleccionar_actividad"),
    path('registrar_retiro/', views.registrar_retiro, name='registrar_retiro'),
    path('destinos/', views.destinos_list_create, name='destinos'),
    path('destinos/editar/<int:destino_id>/', views.destinos_list_create, name='destino_editar'),
    path("destinos/eliminar/<int:id>/", views.destino_eliminar, name="destino_eliminar"),
    path("api/destinos-por-tipo/", views.destinos_por_tipo, name="destinos_por_tipo"),
    path("reportes/residuos.xlsx", views.exportar_residuos_excel, name="exportar_residuos_excel"),
    path("reportes/retiros.xlsx", views.exportar_retiros_excel, name="exportar_retiros_excel"),
    path("talleres/<int:id>/exportaciones/reintentar/", views.reintentar_exportacion_taller, name="reintentar_exportacion_taller"),
    path("backup/base-datos/", views.generar_backup_db, name="generar_backup_db"),
    path("health/", views.health_check, name="health_check"),

]
