"""
Django settings for codigo_qr project.

Generated by 'django-admin startproject' using Django 5.0.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path):
    """Carga variables simples KEY=VALUE desde .env sin depender de rutas locales."""
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on", "si", "sí"}


def _env_int(name, default):
    value = os.environ.get(name)
    if value in (None, ""):
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} debe ser un numero entero.") from exc


def _env_list(name, default=None):
    raw = os.environ.get(name)
    if raw is None:
        return list(default or [])
    return [item.strip() for item in raw.split(",") if item.strip()]


def _env_path(name, default):
    raw = os.environ.get(name)
    if not raw:
        return Path(default)
    path = Path(raw)
    return path if path.is_absolute() else BASE_DIR / path


_load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-change-this-key-in-production"
)

# SECURITY WARNING: don't run with debug turned on in production.
DEBUG = _env_bool("DJANGO_DEBUG", True)

if not DEBUG and (
    # Bandit B105: centinela que bloquea una configuración insegura, no un secreto real.
    SECRET_KEY == "django-insecure-dev-change-this-key-in-production"  # nosec B105
    or SECRET_KEY.startswith("cambie-")
):
    raise ImproperlyConfigured(
        "Defina DJANGO_SECRET_KEY en .env o en el entorno antes de usar DJANGO_DEBUG=False."
    )

ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    ["localhost", "127.0.0.1", "testserver", "proyectotitulo.pythonanywhere.com"],
)
if DEBUG and os.environ.get("DJANGO_ALLOWED_HOSTS") is None:
    ALLOWED_HOSTS.append("*")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'app.middleware.MinimalPermissionsPolicyMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'codigo_qr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.grupos_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'codigo_qr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": _env_path("DJANGO_DB_NAME", BASE_DIR / "db.sqlite3"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
    },
    {
        'NAME': 'app.password_validators.StrongPasswordValidator',
        'OPTIONS': {
            'min_length': 8,
            'max_length': 12,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = os.environ.get("DJANGO_STATIC_URL", "/static/")
STATIC_ROOT = _env_path("DJANGO_STATIC_ROOT", BASE_DIR / "staticfiles")
PROJECT_STATIC_DIR = BASE_DIR / "static"
STATICFILES_DIRS = []
if PROJECT_STATIC_DIR.exists() and any(path.name != "admin" for path in PROJECT_STATIC_DIR.iterdir()):
    STATICFILES_DIRS.append(PROJECT_STATIC_DIR)

MEDIA_URL = os.environ.get("DJANGO_MEDIA_URL", "/media/")
MEDIA_ROOT = _env_path("DJANGO_MEDIA_ROOT", BASE_DIR / "media")
EXPORT_DIR = _env_path("DJANGO_EXPORT_DIR", BASE_DIR / "exportaciones")
BACKUP_DIR = _env_path("DJANGO_BACKUP_DIR", BASE_DIR / "backups")
ROLLING_BACKUP_FILENAME = os.environ.get(
    "DJANGO_ROLLING_BACKUP_FILENAME",
    "respaldo_base_datos.sqlite3",
)
CLASS_BACKUP_LEAD_SECONDS = _env_int("CLASS_BACKUP_LEAD_SECONDS", 30)
WORKSHOP_WORKER_INTERVAL_SECONDS = _env_int("WORKSHOP_WORKER_INTERVAL_SECONDS", 10)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
URL_UPDATE = os.environ.get("DJANGO_WEIGHT_UPDATE_URL", "/api/update_weight/")
PUBLIC_BASE_URL = os.environ.get("DJANGO_PUBLIC_BASE_URL", "")
WEIGHT_API_TOKEN = os.environ.get("WEIGHT_API_TOKEN", "")
MAX_WEIGHT_KG = os.environ.get("MAX_WEIGHT_KG", "1000")
WEIGHT_READING_MAX_AGE_SECONDS = _env_int("WEIGHT_READING_MAX_AGE_SECONDS", 10)
WEIGHT_BRIDGE_FIRST = _env_bool("WEIGHT_BRIDGE_FIRST", True)
WEIGHT_DIRECT_READ_ENABLED = _env_bool("WEIGHT_DIRECT_READ_ENABLED", True)
BALANZA_SERIAL_PORTS = _env_list("BALANZA_SERIAL_PORTS", [])
BALANZA_SERIAL_BAUDRATES = _env_list(
    "BALANZA_SERIAL_BAUDRATES",
    ["9600", "4800", "2400", "1200", "19200", "38400", "57600", "115200"],
)
BALANZA_SERIAL_MODES = _env_list(
    "BALANZA_SERIAL_MODES",
    ["8N1", "7E1", "8E1", "7N1", "8N2"],
)
BALANZA_LINE_CONTROLS = _env_list(
    "BALANZA_LINE_CONTROLS",
    ["default", "rts", "dtr_rts", "none"],
)
BALANZA_PROBE_SECONDS = _env_int("BALANZA_PROBE_SECONDS", 2)
BALANZA_SCAN_TIMEOUT_SECONDS = _env_int("BALANZA_SCAN_TIMEOUT_SECONDS", 20)
BALANZA_STABLE_SAMPLES = _env_int("BALANZA_STABLE_SAMPLES", 3)
BALANZA_STABLE_TOLERANCE_KG = os.environ.get("BALANZA_STABLE_TOLERANCE_KG", "0.020")
BALANZA_POLL_COMMANDS = _env_list(
    "BALANZA_POLL_COMMANDS",
    ["", "S\\r\\n", "W\\r\\n", "P\\r\\n", "SI\\r\\n", "Q\\r\\n", "PRINT\\r\\n"],
)
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

CSRF_TRUSTED_ORIGINS = _env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    ["https://proyectotitulo.pythonanywhere.com"],
)

# Solo estas direcciones pueden informar la IP original mediante
# X-Forwarded-For. Si la lista está vacía siempre se usa REMOTE_ADDR.
TRUSTED_PROXY_IPS = set(_env_list("DJANGO_TRUSTED_PROXY_IPS", []))

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = _env_int("DJANGO_SESSION_COOKIE_AGE", 14400)
SESSION_EXPIRE_AT_BROWSER_CLOSE = _env_bool("DJANGO_SESSION_EXPIRE_AT_BROWSER_CLOSE", False)
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
if _env_bool("DJANGO_USE_X_FORWARDED_PROTO", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
DATA_UPLOAD_MAX_MEMORY_SIZE = _env_int("DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE", 5 * 1024 * 1024)

PASSWORD_MAX_AGE_DAYS = _env_int("PASSWORD_MAX_AGE_DAYS", 120)
ENFORCE_INSTITUTIONAL_EMAIL_DOMAIN = _env_bool("ENFORCE_INSTITUTIONAL_EMAIL_DOMAIN", True)
INSTITUTIONAL_EMAIL_DOMAINS = [
    domain.lower()
    for domain in _env_list("INSTITUTIONAL_EMAIL_DOMAINS", ["inacap.cl", "inacapmail.cl"])
]
USE_INSTITUTIONAL_BRAND = _env_bool("USE_INSTITUTIONAL_BRAND", True)
LOGIN_MAX_ATTEMPTS = _env_int("LOGIN_MAX_ATTEMPTS", 5)
LOGIN_LOCKOUT_SECONDS = _env_int("LOGIN_LOCKOUT_SECONDS", 900)

# Correo de confirmación de altas. En desarrollo se imprime en consola; en
# producción se configura mediante SMTP institucional sin guardar secretos.
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    (
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "smtp.office365.com")
EMAIL_PORT = _env_int("DJANGO_EMAIL_PORT", 587)
EMAIL_USE_TLS = _env_bool("DJANGO_EMAIL_USE_TLS", True)
EMAIL_USE_SSL = _env_bool("DJANGO_EMAIL_USE_SSL", False)
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_TIMEOUT = _env_int("DJANGO_EMAIL_TIMEOUT", 15)
DEFAULT_FROM_EMAIL = os.environ.get(
    "DJANGO_DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER or "no-reply@localhost",
)

DATA_RETENTION_DAYS = _env_int("DATA_RETENTION_DAYS", 1095)
AUDIT_LOG_RETENTION_DAYS = _env_int("AUDIT_LOG_RETENTION_DAYS", 365)
WEIGHT_READING_RETENTION_DAYS = _env_int("WEIGHT_READING_RETENTION_DAYS", 365)
BACKUP_RETENTION_DAYS = _env_int("BACKUP_RETENTION_DAYS", 180)

HEALTH_CHECK_REQUIRE_LOGIN = _env_bool("DJANGO_HEALTH_CHECK_REQUIRE_LOGIN", not DEBUG)
HEALTH_CHECK_EXPOSE_DETAILS = _env_bool("DJANGO_HEALTH_CHECK_EXPOSE_DETAILS", DEBUG)

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_HSTS_SECONDS = _env_int("DJANGO_HSTS_SECONDS", 31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

LOG_DIR = _env_path("DJANGO_LOG_DIR", BASE_DIR / "logs")
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "django.log",
            "maxBytes": 1024 * 1024,
            "backupCount": 5,
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": True,
        },
        "app": {
            "handlers": ["console", "file"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}
